### ISSUE TITLE
Selecting tram twice  is problem

### ISSUE THREAD

**Issue by Rogiervanarkel** [hermanbanken/LightRailGame#8]
In Tutorial:

Select a tram. 
Push Esc.
Select same tram again. --> does not work
Select other tram
Push Esc
select first tram -> OK

**Comment by Rogiervanarkel** [comment]
If anything else is clicked first the tram can be selected again!!

**Comment by Rogiervanarkel** [comment]
If anything else is clicked the tram can be selected again.

**Comment by hermanbanken** [comment]
Fixed today
